# Local development dependencies including docs building, website upload, ASV benchmark
name: pandas-dev
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip

  # build dependencies
  - versioneer[toml]
  - cython=0.29.32

  # test dependencies
  - pytest>=6.0
  - pytest-cov
  - pytest-xdist>=1.31
  - psutil
  - pytest-asyncio>=0.17
  - coverage

  # required dependencies
  - python-dateutil
  - numpy
  - pytz

  # optional dependencies
  - beautifulsoup4
  - blosc
  - brotlipy
  - bottleneck
  - fastparquet
  - fsspec
  - html5lib
  - hypothesis
  - gcsfs
  - ipython
  - jinja2
  - lxml
  - matplotlib>=3.6.1
  - numba>=0.53.1
  - numexpr>=2.8.0  # pin for "Run checks on imported code" job
  - openpyxl
  - odfpy
  - py
  - psycopg2
  - pyarrow<10
  - pymysql
  - pyreadstat
  - pytables
  - python-snappy
  - pyxlsb
  - s3fs>=2021.08.0
  - scipy
  - sqlalchemy
  - tabulate
  - tzdata>=2022a
  - xarray
  - xlrd
  - xlsxwriter
  - zstandard

  # downstream packages
  - aiobotocore<2.0.0  # GH#44311 pinned to fix docbuild
  - dask-core
  - seaborn-base

  # local testing dependencies
  - moto
  - flask

  # benchmarks
  - asv

  # The compiler packages are meta-packages and install the correct compiler (activation) packages on the respective platforms.
  - c-compiler
  - cxx-compiler

  # code checks
  - black=22.10.0
  - cpplint
  - flake8=6.0.0
  - flake8-bugbear=22.7.1 # used by flake8, find likely bugs
  - isort>=5.2.1  # check that imports are in the right order
  - mypy=0.990
  - pre-commit>=2.15.0
  - pycodestyle  # used by flake8
  - pyupgrade

  # documentation
  - gitpython  # obtain contributors from git for whatsnew
  - gitdb
  - natsort  # DataFrame.sort_values doctest
  - numpydoc
  - pandas-dev-flaker=0.5.0
  - pydata-sphinx-theme<0.11
  - pytest-cython  # doctest
  - sphinx
  - sphinx-panels
  - sphinx-copybutton
  - types-python-dateutil
  - types-PyMySQL
  - types-pytz
  - types-setuptools

  # documentation (jupyter notebooks)
  - nbconvert>=6.4.5
  - nbsphinx
  - pandoc
  - ipywidgets
  - nbformat
  - notebook>=6.0.3
  - ipykernel

  # web
  - jinja2  # in optional dependencies, but documented here as needed
  - markdown
  - feedparser
  - pyyaml
  - requests

  - pip:
      - sphinx-toggleprompt
